# Generated by Django 4.2.7 on 2024-01-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='student Name')),
                ('email', models.EmailField(max_length=255, verbose_name='student Email')),
            ],
        ),
    ]
